// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCTsDi1Gxvbkyu6x6GAIAB5GGXFPeLBu4',
    appId: '1:205603761672:web:4e86c0abde85739b262bbd',
    messagingSenderId: '205603761672',
    projectId: 'money-mgt-7be3a',
    authDomain: 'money-mgt-7be3a.firebaseapp.com',
    storageBucket: 'money-mgt-7be3a.firebasestorage.app',
    measurementId: 'G-MB8YQHTV62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidiPcrE5RgWfMnu3soHTgEeEKcIg8p54',
    appId: '1:205603761672:android:81aeea75b3a6f9b5262bbd',
    messagingSenderId: '205603761672',
    projectId: 'money-mgt-7be3a',
    storageBucket: 'money-mgt-7be3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0jMjxASB0x2A5Gr2lt_UzxMx3-juj16Y',
    appId: '1:205603761672:ios:3bb51e412ed77133262bbd',
    messagingSenderId: '205603761672',
    projectId: 'money-mgt-7be3a',
    storageBucket: 'money-mgt-7be3a.firebasestorage.app',
    iosBundleId: 'com.example.moneymanager.moneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0jMjxASB0x2A5Gr2lt_UzxMx3-juj16Y',
    appId: '1:205603761672:ios:3bb51e412ed77133262bbd',
    messagingSenderId: '205603761672',
    projectId: 'money-mgt-7be3a',
    storageBucket: 'money-mgt-7be3a.firebasestorage.app',
    iosBundleId: 'com.example.moneymanager.moneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCTsDi1Gxvbkyu6x6GAIAB5GGXFPeLBu4',
    appId: '1:205603761672:web:bbfa97182c2f6a0b262bbd',
    messagingSenderId: '205603761672',
    projectId: 'money-mgt-7be3a',
    authDomain: 'money-mgt-7be3a.firebaseapp.com',
    storageBucket: 'money-mgt-7be3a.firebasestorage.app',
    measurementId: 'G-X95C7SKGMV',
  );
}
