// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcgAQ1pgoxGIvMFC2cgcZ74BBwXlNjx8g',
    appId: '1:599311229904:web:ebfa3f787a7b52f28a4fd5',
    messagingSenderId: '599311229904',
    projectId: 'wmp-final-bc9a6',
    authDomain: 'wmp-final-bc9a6.firebaseapp.com',
    storageBucket: 'wmp-final-bc9a6.firebasestorage.app',
    measurementId: 'G-77MXPZKXVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjWYwyPLfFtAxEznYdVY7F2uRcFTr85k',
    appId: '1:599311229904:android:07b77cc2d95d4a9f8a4fd5',
    messagingSenderId: '599311229904',
    projectId: 'wmp-final-bc9a6',
    storageBucket: 'wmp-final-bc9a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr2U_L_xz0VKmJooWjIZ1N8QXcXO5kdTQ',
    appId: '1:599311229904:ios:d0f380d5a2d069b28a4fd5',
    messagingSenderId: '599311229904',
    projectId: 'wmp-final-bc9a6',
    storageBucket: 'wmp-final-bc9a6.firebasestorage.app',
    iosBundleId: 'com.example.moneymanager.moneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0jMjxASB0x2A5Gr2lt_UzxMx3-juj16Y',
    appId: '1:205603761672:ios:3bb51e412ed77133262bbd',
    messagingSenderId: '205603761672',
    projectId: 'money-mgt-7be3a',
    storageBucket: 'money-mgt-7be3a.firebasestorage.app',
    iosBundleId: 'com.example.moneymanager.moneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcgAQ1pgoxGIvMFC2cgcZ74BBwXlNjx8g',
    appId: '1:599311229904:web:84eb1d10cc0ebe458a4fd5',
    messagingSenderId: '599311229904',
    projectId: 'wmp-final-bc9a6',
    authDomain: 'wmp-final-bc9a6.firebaseapp.com',
    storageBucket: 'wmp-final-bc9a6.firebasestorage.app',
    measurementId: 'G-PD4PJF4E53',
  );

}